import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { parse, stringify } from "yaml";

import { atomicWrite, folder } from "./paths.js";

/**
 * One record, one file, one folder per kind.
 *
 * Every store in the app is the same four operations over YAML files
 * named by id, so there is one of them rather than one per record type.
 * The shape of a record is enforced by its TypeScript type; this only
 * knows how to read and write.
 *
 * YAML rather than JSON because these files are committed and read by
 * people: a diff on a changed acceptance criterion should show the
 * sentence, not a re-wrapped line of escaped JSON.
 */
export interface Keyed {
  id: string;
}

export class Records<T extends Keyed> {
  constructor(
    private readonly name: string,
    /** Filled in for fields a file written by an older version lacks. */
    private readonly defaults: Partial<T> = {},
  ) {}

  private dir(projectPath: string): string {
    return folder(projectPath, this.name);
  }

  private file(projectPath: string, id: string): string {
    // An id is used as a filename, so it must not be able to leave the
    // folder. Ids are generated by the app or checked on import, and this
    // is the last line of defence.
    const safe = id.replace(/[^A-Za-z0-9._-]/g, "_");
    return join(this.dir(projectPath), `${safe}.yaml`);
  }

  list(projectPath: string): T[] {
    const dir = this.dir(projectPath);
    if (!existsSync(dir)) return [];

    const found: T[] = [];
    for (const name of readdirSync(dir)) {
      if (!name.endsWith(".yaml")) continue;
      try {
        const record = parse(readFileSync(join(dir, name), "utf8")) as T;
        if (record && typeof record === "object") found.push({ ...this.defaults, ...record });
      } catch {
        // A file that will not parse is skipped here and reported by
        // `unreadable`, so a corrupt record never silently becomes an
        // absent one.
      }
    }
    found.sort((left, right) => String(left.id).localeCompare(String(right.id)));
    return found;
  }

  /** Files that could not be read, so a gap can be shown rather than hidden. */
  unreadable(projectPath: string): string[] {
    const dir = this.dir(projectPath);
    if (!existsSync(dir)) return [];

    const broken: string[] = [];
    for (const name of readdirSync(dir)) {
      if (!name.endsWith(".yaml")) continue;
      try {
        parse(readFileSync(join(dir, name), "utf8"));
      } catch (error) {
        broken.push(`${name}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
    return broken;
  }

  get(projectPath: string, id: string): T | null {
    const file = this.file(projectPath, id);
    if (!existsSync(file)) return null;
    try {
      const record = parse(readFileSync(file, "utf8")) as T;
      return record ? { ...this.defaults, ...record } : null;
    } catch {
      return null;
    }
  }

  save(projectPath: string, record: T): void {
    atomicWrite(this.file(projectPath, record.id), stringify(record, { lineWidth: 0 }));
  }

  saveAll(projectPath: string, records: T[]): void {
    for (const record of records) this.save(projectPath, record);
  }

  remove(projectPath: string, id: string): void {
    rmSync(this.file(projectPath, id), { force: true });
  }

  /** Empties the folder, keeping it, so the layout stays the same. */
  clear(projectPath: string): void {
    const dir = this.dir(projectPath);
    rmSync(dir, { recursive: true, force: true });
    mkdirSync(dir, { recursive: true });
  }

  count(projectPath: string): number {
    const dir = this.dir(projectPath);
    if (!existsSync(dir)) return 0;
    return readdirSync(dir).filter((name) => name.endsWith(".yaml")).length;
  }
}
